require('./bootstrap');
import $ from 'jquery';
window.$ = window.jQuery = $;
import 'datatables.net-searchpanes-bs4';
import 'datatables.net-select-bs4';
var moment = require('moment');
window.moment = moment;
import 'datatables.net-bs4';
import 'datatables.net-dt';
import 'datatables.net';
