<?php

return [
    'height' => [
        '130' => 'Less than 130cm',
        '131' => '131cm',
        '132' => '132cm',
        '133' => '133cm', 
        '134' => '134cm', 
        '135' => '135cm', 
        '136' => '136cm', 
        '137' => '137cm', 
        '138' => '138cm', 
        '139' => '139cm', 
        '140' => '140cm', 
        '141' => '141cm', 
        '142' => '142cm', 
        '143' => '143cm', 
        '144' => '144cm', 
        '145' => '145cm', 
        '146' => '146cm', 
        '147' => '147cm', 
        '148' => '148cm', 
        '149' => '149cm', 
        '150' => '150cm', 
        '151' => '151cm', 
        '152' => '152cm', 
        '153' => '153cm', 
        '154' => '154cm', 
        '155' => '155cm', 
        '156' => '156cm', 
        '157' => '157cm', 
        '158' => '158cm', 
        '159' => '159cm', 
        '160' => '160cm', 
        '161' => '161cm', 
        '162' => '162cm', 
        '163' => '163cm', 
        '164' => '164cm', 
        '165' => '165cm', 
        '166' => '166cm', '167' => '167cm', '168' => '168cm', '169' => '169cm', '170' => '170cm', '171' => '171cm', '172' => '172cm', '173' => '173cm', '174' => '174cm', '175' => '175cm', '176' => '176cm', '177' => '177cm', '178' => '178cm', '179' => '179cm', '180' => '180cm', '181' => '181cm', '182' => '182cm', '183' => '183cm', '184' => '184cm', '185' => '185cm', '186' => '186cm', '187' => '187cm', '188' => '188cm', '189' => '189cm', '190' => '190cm', '191' => '191cm', '192' => '192cm', '193' => '193cm', '194' => '194cm', '195' => '195cm', '196' => '196cm', '197' => '197cm', '198' => '198cm', '199' => '199cm', 
        '200' => 'Above 200cm'
    ],

    'figure' => [
        '1' => "Not selected",
        '2' => 'Slim',
        '3' => 'Slightly thin',
        '4' => 'Nomal',
        '5' => 'Glamor',
        '6' => 'Muscular',
        '7' => 'Slightly Chubby'

    ],

    'matching_expect' => [
        '1' => 'Not selected',
        '2' => 'I want to meet you first after matching',
        '3' => 'I want to see you if you feel like it',
        '4' => 'I want to see you if the conditions are met',
        '5' => 'I want to meet after exchanging messages'
    ],

    'job' => [
        '1' => ['1' => 'Not selected', '0' => 'Not selected'],
        '2' => ['1' => 'Office worker', '0' => 'Office worker'],
        '3' => ['1' => 'Doctor', '0' => 'Doctor'],
        '4' => ['1' => 'Lawyer', '0' => 'Lawyer'],
        '5' => ['1' => 'Certified Public Accountant', '0' => 'Certified Public Accountant'],
        '6' => ['1' => 'Manager / Executive', '0' => 'Manager / Executive'],
        '7' => ['1' => 'Public servant', '0' => 'Public servant'],
        '8' => ['1' => 'Clerk', '0' => 'Clerk'],
        '9' => ['1' => 'Major trading company', '0' => 'Major trading company'],
        '10' => ['1' => 'Foreign Finance', '0' => 'Foreign Finance'],
        '11' => ['1' => 'Big company', '0' => 'Big company'],
        '12' => ['1' => 'Major foreign capital', '0' => 'Major foreign capital'],
        '13' => ['1' => 'Creator', '0' => 'Creator'],
        '14' => ['1' => 'IT related', '0' => 'IT related'],
        '15' => ['1' => 'Pilot', '0' => ''],
        '16' => ['1' => 'Entertainment / Model', '0' => 'Entertainment / Model'],
        '17' => ['1' => 'Apparel', '0' => 'Apparel'],
        '18' => ['1' => 'Announcer', '0' => ''],
        '19' => ['1' => 'Nursery teacher', '0' => ''],
        '20' => ['1' => 'Dentist', '0' => 'Dentist'],
        '21' => ['1' => 'Student', '0' => 'Student'],
        '22' => ['1' => 'Other', '0' => 'Other'],
        '23' => ['1' => 'Entertainment', '0' => ''],
        '24' => ['1' => 'Bridal', '0' => 'Finance'],
        '25' => ['1' => 'Welfare / Nursing', '0' => 'Consulting'],
        '26' => ['1' => 'Advertising', '0' => 'Cook / Nutritionist'],
        '27' => ['1' => 'Media', '0' => 'Educational'],
        '28' => ['1' => 'Freeter', '0' => 'Food related'],
        '29' => ['1' => 'Customer service', '0' => 'Pharmaceutical'],
        '30' => ['1' => 'Nurse', '0' => 'Insurance'],
        '31' => ['1' => 'Reception', '0' => 'Real estate'],
        '32' => ['1' => 'Freeter', '0' => 'architecture'],
        '33' => ['1' => 'Secretary', '0' => 'communication'],
        '34' => ['1' => 'Flight attendants', '0' => 'Distribution'],
        '35' => ['1' => 'Event Companion', '0' => 'Web Industry'],
        '36' => ['1' => 'Finance', '0' => ''],
        '37' => ['1' => 'Consulting', '0' => 'Entertainment'],
        '38' => ['1' => 'Cook / nutritionist', '0' => 'Bridal'],
        '39' => ['1' => 'Education-related', '0' => 'Welfare / long-term care'],
        '40' => ['1' => 'Food related', '0' => 'Advertising'],
        '41' => ['1' => 'Pharmaceutical', '0' => 'Media'],
        '42' => ['1' => 'Insurance', '0' => 'Feeter'],
        '43' => ['1' => 'Real estate', '0' => ''],
        '44' => ['1' => 'Architecture', '0' => ''],
        '45' => ['1' => 'Communication', '0' => ''],
        '46' => ['1' => 'Circulation', '0' => ''],
        '47' => ['1' => 'Web Industry', '0' => '']

    ],

    'anual_income' => [
        '1' => ['1' => 'Not selected', '0' => 'Not selected'],
        '2' => ['1' => '3-6 million', '0' => '3-6 million'],
        '3' => ['1' => '6-9 million', '0' => '6-9 million'],
        '4' => ['1' => '9-12 million', '0' => '9-12 million'],
        '5' => ['1' => '12-15 million', '0' => '12-15 million'],
        '6' => ['1' => '15-18 million', '0' => '15-18 million'],
        '7' => ['1' => '18-30 million', '0' => '18-30 million'],
        '8' => ['1' => 'more than 30 million', '0' => 'more than 30 million']
    ],
    'holiday' => [
        '1' => ['1' => 'Not selected', '0' => 'Not selected'],
        '2' => ['1' => 'Saturday and Sunday', '0' => 'Saturday and Sunday'],
        '3' => ['1' => 'Weekdays', '0' => 'Weekdays'],
        '4' => ['1' => 'Irregular', '0' => 'Irregular'],
        '5' => ['1' => 'Other', '0' => 'Other']
    ],
    'aca_background' => [
        '1' => ['1' => 'Not selected', '0' => 'Not selected'],
        '2' => ['1' => 'High school graduate', '0' => 'High school graduate'],
        '3' => ['1' => 'Vocational school', '0' => 'Vocational school'],
        '4' => ['1' => 'University graduate', '0' => 'University graduate'],
        '5' => ['1' => 'Graduate school graduate', '0' => 'Graduate school graduate'],
        '6' => ['1' => 'Other', '0' => 'Other']
    ],
    'alcohol' => [
        '1' => ['1' => 'Not selected', '0' => 'Not selected'],
        '2' => ['1' => "Don't drink", '0' => "Don't drink"],
        '3' => ['1' => 'Drink', '0' => 'Drink'],
        '4' => ['1' => 'Drink from time to time', '0' => 'Drink from time to time']

    ],
    'tabaco' => [
        '1' => ['1' => 'Not selected', '0' => 'Not selected'],
        '2' => ['1' => "Don't smoke", '0' => "Don't smoke"],
        '3' => ['1' => 'Suck', '0' => 'Suck'],
        '4' => ['1' => 'Sometimes smoke', '0' => 'Sometimes smoke'],
        '5' => ['1' => "Don't smoke in front of non-smokers", '0' => "Stop if you don't like the other person"]

    ],
    'housemate' => [
        '1' => ['1' => 'Not selected', '0' => 'Not selected'],
        '2' => ['1' => 'Living alone', '0' => 'Living alone'],
        '3' => ['1' => 'With friends', '0' => 'With friends'],
        '4' => ['1' => 'With pets', '0' => 'With pets'],
        '5' => ['1' => 'Living at home', '0' => 'Living at home'],
        '6' => ['1' => 'Other', '0' => 'Other']

    ],
    'hobby' => [
        '1' => 'Not selected',
        '2' => 'A kind person',
        '3' => "I don't care about appearance",
        '4' => 'People with a sense of cleanliness',
        '5' => 'Those who can afford',
        '6' => 'Tall person',
        '7' => 'Multiple selections possible'
    ],
    'birthplace' => [
        '1' => 'Not selected',
        '2' => 'Tokyo',
        '3' => 'Kanagawa Prefecture',
        '4' => 'Saitama',
        '5' => 'Chiba',
        '6' => 'Osaka',
        '7' => 'Kyoto',
        '8' => 'Hyogo prefecture',
        '9' => 'Nara Prefecture',
        '10' => 'Aichi prefecture',
        '11' => 'Gifu Prefecture',
        '12' => 'Mie Prefecture',
        '13' => 'Fukuoka Prefecture',
        '14' => 'Hokkaido',
        '15' => 'Aomori Prefecture',
        '16' => 'Iwate Prefecture',
        '17' => 'Miyagi Prefecture',
        '18' => 'Akita',
        '19' => 'Yamagata Prefecture',
        '20' => 'Fukushima Prefecture',
        '21' => 'Ibaraki Prefecture',
        '22' => 'Tochigi Prefecture',
        '23' => 'Gunma Prefecture',
        '24' => 'Niigata Prefecture',
        '25' => 'Toyama Prefecture',
        '26' => 'Ishikawa Prefecture',
        '27' => 'Fukui prefecture',
        '28' => 'Yamanashi Prefecture',
        '29' => 'Nagano Prefecture',
        '30' => 'Shizuoka Prefecture',
        '31' => 'Shiga Prefecture',
        '32' => 'Wakayama Prefecture',
        '33' => 'Tottori prefecture',
        '34' => 'Shimane Prefecture',
        '35' => 'Hiroshima Prefecture',
        '36' => 'Mountain Yamaguchi Prefecture',
        '37' => 'Tokushima',
        '38' => 'Kagawa Prefecture',
        '39' => 'Ehime Prefecture',
        '40' => 'Kochi Prefecture',
        '41' => 'Saga Prefecture',
        '42' => 'Nagasaki Prefecture',
        '43' => 'Kumamoto Prefecture',
        '44' => 'Oita Prefecture',
        '45' => 'Miyazaki prefecture',
        '46' => 'Okinawa Prefecture',
        '47' => 'Overseas'
    ],
];
