<?php

return [
    'height' => [
        '130' => '130cm未満',
        '131' => '131cm',
        '132' => '132cm',
        '133' => '133cm', 
        '134' => '134cm', 
        '135' => '135cm', 
        '136' => '136cm', 
        '137' => '137cm', 
        '138' => '138cm', 
        '139' => '139cm', 
        '140' => '140cm', 
        '141' => '141cm', 
        '142' => '142cm', 
        '143' => '143cm', 
        '144' => '144cm', 
        '145' => '145cm', 
        '146' => '146cm', 
        '147' => '147cm', 
        '148' => '148cm', 
        '149' => '149cm', 
        '150' => '150cm', 
        '151' => '151cm', 
        '152' => '152cm', 
        '153' => '153cm', 
        '154' => '154cm', 
        '155' => '155cm', 
        '156' => '156cm', 
        '157' => '157cm', 
        '158' => '158cm', 
        '159' => '159cm', 
        '160' => '160cm', 
        '161' => '161cm', 
        '162' => '162cm', 
        '163' => '163cm', 
        '164' => '164cm', 
        '165' => '165cm', 
        '166' => '166cm', '167' => '167cm', '168' => '168cm', '169' => '169cm', '170' => '170cm', '171' => '171cm', '172' => '172cm', '173' => '173cm', '174' => '174cm', '175' => '175cm', '176' => '176cm', '177' => '177cm', '178' => '178cm', '179' => '179cm', '180' => '180cm', '181' => '181cm', '182' => '182cm', '183' => '183cm', '184' => '184cm', '185' => '185cm', '186' => '186cm', '187' => '187cm', '188' => '188cm', '189' => '189cm', '190' => '190cm', '191' => '191cm', '192' => '192cm', '193' => '193cm', '194' => '194cm', '195' => '195cm', '196' => '196cm', '197' => '197cm', '198' => '198cm', '199' => '199cm', 
        '200' => '200cm以上'
    ],

    'figure' => [
        '1' => "未選択",
        '2' => 'スリム',
        '3' => 'やや細め',
        '4' => '普通',
        '5' => 'グラマー',
        '6' => '筋肉質',
        '7' => 'ややぽっちゃり'

    ],

    'matching_expect' => [
        '1' => '未選択',
        '2' => 'マッチング後はまず会いたい',
        '3' => '気が合えば会いたい',
        '4' => '条件が合えば会いたい',
        '5' => 'メッセージ交換を重ねてから会いたい'
    ],

    'job' => [
        '1' => ['male' => '未選択', 'female' => '未選択'],
        '2' => ['male' => '会社員', 'female' => '会社員'],
        '3' => ['male' => '医者', 'female' => '医者'],
        '4' => ['male' => '弁護士', 'female' => '弁護士'],
        '5' => ['male' => '公認会計士', 'female' => '公認会計士'],
        '6' => ['male' => '経営者・役員', 'female' => '経営者・役員'],
        '7' => ['male' => '公務員', 'female' => '公務員'],
        '8' => ['male' => '事務員', 'female' => '事務員'],
        '9' => ['male' => '大手商社', 'female' => '大手商社'],
        '10' => ['male' => '外資金融', 'female' => '外資金融'],
        '11' => ['male' => '大手企業', 'female' => '大手企業'],
        '12' => ['male' => '大手外資', 'female' => '大手外資'],
        '13' => ['male' => 'クリエイター', 'female' => 'クリエイター'],
        '14' => ['male' => 'IT関連', 'female' => 'IT関連'],
        '15' => ['male' => 'パイロット', 'female' => ''],
        '16' => ['male' => '芸能・モデル', 'female' => '芸能・モデル'],
        '17' => ['male' => 'アパレル', 'female' => 'アパレル'],
        '18' => ['male' => 'アナウンサー', 'female' => ''],
        '19' => ['male' => '保育士', 'female' => ''],
        '20' => ['male' => '歯科医', 'female' => '歯科医'],
        '21' => ['male' => '学生', 'female' => '学生'],
        '22' => ['male' => 'その他', 'female' => 'その他'],
        '23' => ['male' => 'エンタメ', 'female' => ''],
        '24' => ['male' => 'ブライダル', 'female' => '金融'],
        '25' => ['male' => '福祉・介護', 'female' => 'コンサル'],
        '26' => ['male' => '広告', 'female' => '調理師・栄養士'],
        '27' => ['male' => 'マスコミ', 'female' => '教育関連'],
        '28' => ['male' => 'フリーター', 'female' => '食品関連'],
        '29' => ['male' => '接客業', 'female' => '製薬'],
        '30' => ['male' => '看護師', 'female' => '保険'],
        '31' => ['male' => '受付', 'female' => '不動産'],
        '32' => ['male' => 'フリーター', 'female' => '建築関連'],
        '33' => ['male' => '秘書', 'female' => '通信'],
        '34' => ['male' => '客室乗務員', 'female' => '流通'],
        '35' => ['male' => 'イベントコンパニオン', 'female' => 'WEb業界'],
        '36' => ['male' => '金融', 'female' => ''],
        '37' => ['male' => 'コンサル', 'female' => 'エンタメ'],
        '38' => ['male' => '調理師・栄養士', 'female' => 'ブライダル'],
        '39' => ['male' => '教育関連', 'female' => '福祉・介護'],
        '40' => ['male' => '食品関連', 'female' => '広告'],
        '41' => ['male' => '製薬', 'female' => 'マスコミ'],
        '42' => ['male' => '保険', 'female' => 'フリーター'],
        '43' => ['male' => '不動産', 'female' => ''],
        '44' => ['male' => '建築関連', 'female' => ''],
        '45' => ['male' => '通信', 'female' => ''],
        '46' => ['male' => '流通', 'female' => ''],
        '47' => ['male' => 'WEb業界', 'female' => '']

    ],

    'anual_income' => [
        '1' => ['male' => 'Not selected', 'female' => 'Not selected'],
        '2' => ['male' => '3-6 million', 'female' => '3-6 million'],
        '3' => ['male' => '6-9 million', 'female' => '6-9 million'],
        '4' => ['male' => '9-12 million', 'female' => '9-12 million'],
        '5' => ['male' => '12-15 million', 'female' => '12-15 million'],
        '6' => ['male' => '15-18 million', 'female' => '15-18 million'],
        '7' => ['male' => '18-30 million', 'female' => '18-30 million'],
        '8' => ['male' => 'more than 30 million', 'female' => 'more than 30 million']
    ],
    'holiday' => [
        '1' => ['male' => 'Not selected', 'female' => 'Not selected'],
        '2' => ['male' => 'Saturday and Sunday', 'female' => 'Saturday and Sunday'],
        '3' => ['male' => 'Weekdays', 'female' => 'Weekdays'],
        '4' => ['male' => 'Irregular', 'female' => 'Irregular'],
        '5' => ['male' => 'Other', 'female' => 'Other']
    ],
    'aca_background' => [
        '1' => ['male' => 'Not selected', 'female' => 'Not selected'],
        '2' => ['male' => 'High school graduate', 'female' => 'High school graduate'],
        '3' => ['male' => 'Vocational school', 'female' => 'Vocational school'],
        '4' => ['male' => 'University graduate', 'female' => 'University graduate'],
        '5' => ['male' => 'Graduate school graduate', 'female' => 'Graduate school graduate'],
        '6' => ['male' => 'Other', 'female' => 'Other']
    ],
    'alcohol' => [
        '1' => ['male' => 'Not selected', 'female' => 'Not selected'],
        '2' => ['male' => "Don't drink", 'female' => "Don't drink"],
        '3' => ['male' => 'Drink', 'female' => 'Drink'],
        '4' => ['male' => 'Drink from time to time', 'female' => 'Drink from time to time']

    ],
    'tabaco' => [
        '1' => ['male' => 'Not selected', 'female' => 'Not selected'],
        '2' => ['male' => "Don't smoke", 'female' => "Don't smoke"],
        '3' => ['male' => 'Suck', 'female' => 'Suck'],
        '4' => ['male' => 'Sometimes smoke', 'female' => 'Sometimes smoke'],
        '5' => ['male' => "Don't smoke in front of non-smokers", 'female' => "Stop if you don't like the other person"]

    ],
    'housemate' => [
        '1' => ['male' => 'Not selected', 'female' => 'Not selected'],
        '2' => ['male' => 'Living alone', 'female' => 'Living alone'],
        '3' => ['male' => 'With friends', 'female' => 'With friends'],
        '4' => ['male' => 'With pets', 'female' => 'With pets'],
        '5' => ['male' => 'Living at home', 'female' => 'Living at home'],
        '6' => ['male' => 'Other', 'female' => 'Other']

    ],
    'hobby' => [
        '1' => 'Not selected',
        '2' => 'A kind person',
        '3' => "I don't care about appearance",
        '4' => 'People with a sense of cleanliness',
        '5' => 'Those who can afford',
        '6' => 'Tall person',
        '7' => 'Multiple selections possible'
    ],
    'birthplace' => [
        '1' => 'Please choose',
        '2' => 'Tokyo',
        '3' => 'Kanagawa Prefecture',
        '4' => 'Saitama',
        '5' => 'Chiba',
        '6' => 'Osaka',
        '7' => 'Kyoto',
        '8' => 'Hyogo prefecture',
        '9' => 'Nara Prefecture',
        '10' => 'Aichi prefecture',
        '11' => 'Gifu Prefecture',
        '12' => 'Mie Prefecture',
        '13' => 'Fukuoka Prefecture',
        '14' => 'Hokkaido',
        '15' => 'Aomori Prefecture',
        '16' => 'Iwate Prefecture',
        '17' => 'Miyagi Prefecture',
        '18' => 'Akita',
        '19' => 'Yamagata Prefecture',
        '20' => 'Fukushima Prefecture',
        '21' => 'Ibaraki Prefecture',
        '22' => 'Tochigi Prefecture',
        '23' => 'Gunma Prefecture',
        '24' => 'Niigata Prefecture',
        '25' => 'Toyama Prefecture',
        '26' => 'Ishikawa Prefecture',
        '27' => 'Fukui prefecture',
        '28' => 'Yamanashi Prefecture',
        '29' => 'Nagano Prefecture',
        '30' => 'Shizuoka Prefecture',
        '31' => 'Shiga Prefecture',
        '32' => 'Wakayama Prefecture',
        '33' => 'Tottori prefecture',
        '34' => 'Shimane Prefecture',
        '35' => 'Hiroshima Prefecture',
        '36' => '山Yamaguchi Prefecture口県',
        '37' => 'Tokushima',
        '38' => 'Kagawa Prefecture',
        '39' => 'Ehime Prefecture',
        '40' => 'Kochi Prefecture',
        '41' => 'Saga Prefecture',
        '42' => 'Nagasaki Prefecture',
        '43' => 'Kumamoto Prefecture',
        '44' => 'Oita Prefecture',
        '45' => 'Miyazaki prefecture',
        '46' => 'Okinawa Prefecture',
        '47' => 'Overseas'
    ],
];
